# See http://www.appveyor.com/docs/appveyor-yml for many more options

#Publish to PowerShell Gallery with this key
environment:
  PSGalleryNugetApiKey:
    secure: wH1ALRNiAuiA7dS5i4I5dPsQzuoCuV0yHf7Pe/HQn8BOJ/5wSdNqy4aa+N7J2kbn
  GithubAuthToken:
    secure: gN4n/aBQ95awEEv4QPGlV810lNHSqFpxFmXCCTj31wSpvadZ8SMtH9PrxlTYyb9j

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

skip_commits:
  files:
    - README.md

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name"
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
        $env:packageVersion = "$env:APPVEYOR_REPO_TAG_NAME" 
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
        $env:packageVersion = "0.0.1-dev"
      }


build_script:
  - ps: . .\build.ps1

artifacts:
  - path: PPoShTools

deploy:
  - provider: GitHub
    auth_token: $(GithubAuthToken)
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true

after_deploy:
  - ps: Publish-Module -Path ($env:APPVEYOR_BUILD_FOLDER + '\PPoShTools\PPoShTools.psd1') -NuGetApiKey $env:PSGalleryNugetApiKey -Verbose -Force
    on:
      branch: master
      appveyor_repo_tag: true